# Generated by Django 2.0 on 2018-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='yt_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
