# Generated by Django 2.0 on 2018-06-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_votes_yt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='yt_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
