# Generated by Django 2.0 on 2018-06-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180611_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Video',
        ),
    ]
