# Generated by Django 2.0 on 2018-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180611_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='yt_id',
            field=models.CharField(max_length=100),
        ),
    ]
